package ovh.devcraft.vogonpoet.ui.constants

val vogonLoadingStrings =
    arrayOf(
        // The Babel Fish & Decoding (Listening focus)
        "Feeding the Babel Fish...",
        "Decoding brainwaves...",
        "Tuning sub-etha...",
        "Intercepting audio...",
        "Translating frequencies...",
        "Catching the waves...",
        "Decrypting speech...",
        "Absorbing vocals...",
        "Ingesting words...",
        "Sampling sector ZZ9...",
        "Listening in...",
        "Universal translating...",
        "Synapsing...",
        "Scanning voice...",
        "Detecting life forms...",
        "Parsing vocal cords...",
        "Analyzing input...",
        "Digesting dialogue...",
        "Hitchhiking frequencies...",
        "Engaging audio drives...",
        // The Bad Poetry (Writing focus)
        "Composing verses...",
        "Sharpening the quill...",
        "Torturing the alphabet...",
        "Drafting the ode...",
        "Inking the page...",
        "Finding a rhyme...",
        "Mangling the meter...",
        "Scrawling bad poetry...",
        "Preparing the recital...",
        "Forcing a rhyme...",
        "Versifying speech...",
        "Constructing stanzas...",
        "Poetizing input...",
        "Turning audio into agony...",
        "Words into worst...",
        "Scribbling furiously...",
        "Formatting verses...",
        "Capturing the flow...",
        "Rendering rhetoric...",
        "Vogonizing...",
        "Spilling the ink...",
        "Crushing the cadence...",
        "Writing the unreadable...",
        "Summoning synonyms...",
        "Destroying grammar...",
        // Don't Panic & H2G2 References (Lore focus)
        "Don't Panic...",
        "Calculating (not 42)...",
        "Oh freddled gruntbuggly...",
        "Resistance is useless...",
        "Deep Thought processing...",
        "Engaging Improbability...",
        "Consulting the Guide...",
        "Towel at the ready...",
        "Ignoring the mice...",
        "So Long, and Thanks...",
    )
